BASE_URL = "https://careers.google.com/jobs/results/?category="

ENGINNERING_ROLES = [
    'DATA_CENTER_OPERATIONS',
    'DEVELOPER_RELATIONS',
    'INFORMATION_TECHNOLOGY',
     'HARDWARE_ENGINEERING'
]

ENGINNERING_ROLES_FULL = [
    'DATA_CENTER_OPERATIONS',
    'DEVELOPER_RELATIONS',
    'HARDWARE_ENGINEERING',
    'INFORMATION_TECHNOLOGY',
    'MANUFACTURING_SUPPLY_CHAIN',
    'NETWORK_ENGINEERING',
    'PRODUCT_MANAGEMENT',
    'PROGRAM_MANAGEMENT',
    'SOFTWARE_ENGINEERING',
    'TECHNICAL_INFRASTRUCTURE_ENGINEERING',
    'TECHNICAL_SOLUTIONS',
    'TECHNICAL_WRITING'
]