BASE_URL = "https://careers.google.com/jobs/results/?category="

ENGINNERING_ROLES = [
    'DATA_CENTER_OPERATIONS',
    'HARDWARE_ENGINEERING',
    'NETWORK_ENGINEERING',
    'PRODUCT_MANAGEMENT',
    'PROGRAM_MANAGEMENT',
    'SOFTWARE_ENGINEERING',
    'TECHNICAL_INFRASTRUCTURE_ENGINEERING',
    'TECHNICAL_SOLUTIONS',
]